spring.application.name=loanEmiSchedular
spring.datasource.url=jdbc:postgresql://localhost:5432/loanEmiSchedular
spring.datasource.username=postgres
spring.datasource.password=Temp@123456

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update